name: build-packages

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: write
    name: ${{ matrix.arch }}-${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        branch:
          - 23.05.6

    steps:
      - name: extract version from tag
        shell: bash
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          VERSION=${TAG_NAME%%-*}
          echo "CLEAN_VERSION=$VERSION" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: nikkinikki-org/OpenWrt-nikki
          ref: ${{ env.CLEAN_VERSION }}
          path: OpenWrt-nikki

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: luci-app-nikki
          NO_REFRESH_CHECK: true

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/packages/${{ matrix.arch }}/nikki/*.ipk
