name: build-packages

on:
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        branch:
          - openwrt-23.05.6

    steps:
      - name: Extract version from tag
        shell: bash
        run: |
          # 假设 GITHUB_REF 是 refs/tags/v1.25.2-20260316-1
          TAG_NAME=${GITHUB_REF##*/}
          VERSION=${TAG_NAME%%-*}
          echo "CLEAN_VERSION=$VERSION" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: nikkinikki-org/OpenWrt-nikki
          ref: ${{ env.CLEAN_VERSION }}
          path: OpenWrt-nikki

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: luci-app-nikki
          NO_REFRESH_CHECK: true

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: nikki_${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/nikki
